require 'active_record'
require 'hashie-forbidden_attributes'
require 'grape/activerecord/version'
require 'grape/activerecord/activerecord'
require 'grape/activerecord/compatibility_4'
require 'grape/activerecord/compatibility_5'
require 'grape/activerecord/defaults'
